### ISSUE TITLE
Option to disable loading feature

### ISSUE THREAD

**Issue by bmos** [FG-Unofficial-Developers-Guild/FG-Ammunition-Manager#22]
This is the most common compatibility issue due to the char_weapon scripts.

**Comment by kawazoe** [comment]
One specific use case in 5e: http://dnd5e.wikidot.com/feat:crossbow-expert

**Comment by bmos** [comment]
I just went ahead and added support for crossbow expert
https://github.com/bmos/FG-Ammunition-Manager/releases/tag/v3.5-hotfix.1

**Comment by bmos** [comment]
adding a "noload" weapon property in v3.9
