### ISSUE TITLE
Starfinder Users Please Read!

### ISSUE THREAD

**Issue by Wharwick** [FG-Unofficial-Developers-Guild/FG-Ammunition-Manager#37]
When I try to use extension with Starfinder I get occasional errors. FOr example when I try to assign ammo to the 1st level Laser Azimuth Rifle I get script executuon error FG-Ammunition-Manager.../sfrpg_ammolist.lua:9 attempt to index local ammoType 'a nil value'

AM I doing something wrong or does the ammolist.lua need some editing?

Thasnk you

**Comment by bmos** [comment]
The Starfinder implementation is being moved to a new repo:
https://github.com/soxmax/FG-Ammunition-Manager

That is likely due to an error in the extension, as script errors shouldn't occur when assigning ammo. I'm tagging @SoxMax here so he's aware.

**Comment by SoxMax** [comment]
@Wharwick I have forked Ammunition Manager for Starfinder here: https://github.com/SoxMax/FG-Ammunition-Manager
If you could re-report this there it would make tracking easier. I've unfortunately been on call last week and this week so Fantasy Grounds dev time has been limited.

**Comment by bmos** [comment]
Anyone looking to get the Starfinder extension can now do so on the FG Forge.
https://forge.fantasygrounds.com/shop/items/1128/view
